//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace program_mvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailServiceTransaction
    {
        public string DetailServiceID { get; set; }
        public string HeaderID { get; set; }
        public string ServiceID { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
    
        public virtual HeaderTransaction HeaderTransaction { get; set; }
        public virtual Service Service { get; set; }
    }
}
