//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace program_mvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransaction
    {
        public string DetailID { get; set; }
        public string HeaderID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> quantity { get; set; }
        public string status { get; set; }
    
        public virtual HeaderTransaction HeaderTransaction { get; set; }
        public virtual Product Product { get; set; }
    }
}
