//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace program_mvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderTransaction()
        {
            this.DetailServiceTransactions = new HashSet<DetailServiceTransaction>();
            this.DetailTransactions = new HashSet<DetailTransaction>();
        }
    
        public string HeaderID { get; set; }
        public string CustomerID { get; set; }
        public string CashierID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> CustomerCash { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string VoucherID { get; set; }
        public string DebitTransactionID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailServiceTransaction> DetailServiceTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransaction> DetailTransactions { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
