//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace program_mvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHistory
    {
        public string ProductHistoryID { get; set; }
        public string ProductID { get; set; }
        public Nullable<System.DateTime> MgfDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string MeasuringUnit { get; set; }
        public Nullable<int> Stocks { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
