//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace program_mvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruiter
    {
        public string RecruiterID { get; set; }
        public string RecruiterName { get; set; }
        public string RecruiterEmail { get; set; }
        public string recruiterPhoneNumber { get; set; }
        public Nullable<System.DateTime> recruiterDOB { get; set; }
        public string recruiterAddress { get; set; }
        public string recruiterGender { get; set; }
        public Nullable<byte> isActive { get; set; }
    }
}
