//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace program_mvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string StockID { get; set; }
        public string ProductID { get; set; }
        public string MeasuringUnit { get; set; }
        public Nullable<int> ManyIn { get; set; }
        public Nullable<int> AvailableStocks { get; set; }
        public Nullable<int> ManyOut { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<byte> IsRewardItem { get; set; }
        public Nullable<int> RewardStocks { get; set; }
        public Nullable<int> BrokenStocks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
